services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  web:
    build: .
    # ports:
    #   - "8000:8000"
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - sqlite_data:/app/data
      - static:/app/staticfiles
      - media:/app/media
    restart: unless-stopped

  celery_worker:
    build: .
    command: celery -A settings worker -l info
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

  celery_beat:
    build: .
    command: celery -A settings beat -l info
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - sqlite_data:/app/data
    restart: unless-stopped

  flower:
    build: .
    command: sh -c "celery -A settings flower --basic-auth=$$BLOG_FLOWER_USER:$$BLOG_FLOWER_PASSWORD"
    ports:
      - "5555:5555"
    env_file:
      - settings/.env
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/var/www/static:ro
      - media:/var/www/media:ro
    depends_on:
      - web
    restart: unless-stopped


volumes:
  static:
  media:
  sqlite_data: