# Generated by Django 6.0.2 on 2026-03-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('kk', 'Kazakh')], default='en', help_text="User's preferred language", max_length=10, verbose_name='Preferred language'),
        ),
    ]
