# Generated by Django 6.0.2 on 2026-03-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_timezone_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's timezone", max_length=64, verbose_name='Timezone'),
        ),
    ]
